In [ ]:
import torch
import torch.nn as nn

Single neuron

In [ ]:
# class Model(nn.Module):
#   def __init__(self, num_features):
#     super().__init__()
#     self.linear=nn.Linear(num_features,1)
#     self.sigmoid = nn.Sigmoid()
#   def forward(self,features):
#     out=self.linear(features)
#     out = self.sigmoid(out)
#     return out

With Hidden Layer too

In [ ]:
# class Model(nn.Module):
#   def __init__(self, num_features):
#     super().__init__()
#     self.lin1 = nn.Linear(num_features,3)
#     self.relu = nn.ReLU()
#     self.lin2=nn.Linear(3,1)
#     self.sigmoid = nn.Sigmoid()

#   def forward(self, features):
#     out = self.lin1(features)
#     out = self.relu(out)
#     out = self.lin2(out)
#     out= self.sigmoid(out)
#     return out

Sequential Containers

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )
  def forward(self, features):
    out = self.network(features)
    return out

In [ ]:
features = torch.rand(10,5)
model=Model(features.shape[1])
# model.forward(features)
model(features)

tensor([[0.5891],
        [0.6041],
        [0.5990],
        [0.5706],
        [0.5814],
        [0.6013],
        [0.5777],
        [0.5845],
        [0.5688],
        [0.5930]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.lin1.weight

Parameter containing:
tensor([[-0.3294,  0.2539,  0.1923, -0.0058,  0.0809],
        [ 0.1794, -0.0245, -0.1607, -0.1512,  0.1484],
        [-0.2579, -0.3888, -0.2228, -0.3343, -0.4120]], requires_grad=True)

In [ ]:
model.lin2.weight

Parameter containing:
tensor([[0.3599, 0.3734, 0.0473]], requires_grad=True)